{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "1" %}

package:
  name: 11-id-chx-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0
  noarch: python

requirements:
  run:
    - chxtools
    - suitcase-specfile
