{% set version = "3.1.1" %}

package:
    name: uncertainties
    version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uncertainties/uncertainties-{{ version }}.tar.gz
  sha256: 18b184110cbe31303d25a7bc7f73d51b9cb4e15563cb9aa25ccfbd0ebe07d448

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - uncertainties
    - uncertainties.unumpy
  requires:
    - numpy

about:
  home: https://pypi.python.org/pypi/uncertainties
  license: BSD 3-Clause
  summary: 'Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.'

extra:
  recipe-maintainers:
    - ocefpaf
