{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "1" %}

package:
  name: 07-bm-qas-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - hxntools
    - qastools
    - suitcase-tiff
    - xraylarch
