{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "0" %}

package:
  name: 02-id-six-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 3

requirements:
  run:
    - edrixs
    - pycentroids
    - scikit-learn
    - sixtools >=0.0.2
