{% set name = "pyCHX" %}
{% set version = "4.0.7" %}
{% set token = environ.get('GH_TOKEN') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://{{ token }}@github.com/NSLS-II/{{ name }}.git
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python

  run:
    - python
    - cython
    - dask
    - databroker
    - dill
    - eiger-io
    - h5py
    - lmfit
    - matplotlib
    - modestimage
    - numpy
    - pandas
    - pillow
    - pyolog
    - pyyaml
    - reportlab
    - scikit-beam
    - scikit-image
    - scipy
    - theano
    - tifffile
    - tqdm
    - xray-vision

test:
  imports:
    - pyCHX

about:
  home: https://github.com/NSLS-II/pyCHX
  license: BSD
