{% set name = "pyCHX" %}
{% set version = "4.0.8" %}
{% set token = environ.get('GH_TOKEN') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://{{ token }}@github.com/NSLS-II/{{ name }}.git
  git_rev: v{{ version }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cython
    - dask
    - databroker
    - dill
    - eiger-io
    - h5py
    - lmfit
    - matplotlib
    - modestimage
    - numpy
    - pandas
    - pillow
    - pyolog
    - pytables
    - pyyaml
    - reportlab
    - scikit-beam
    - scikit-image
    - scipy
    - theano
    - tifffile
    - tqdm
    - xray-vision

test:
  imports:
    - pyCHX

about:
  home: https://github.com/NSLS-II/pyCHX
  license: BSD
