{% set org = "NSLS-II-SIX" %}
{% set name = "sixtools" %}
{% set version = "0.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ org }}/{{ name }}/
  git_rev: v{{ version }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python

  run:
    - python
    - rixs >=0.0.2

test:
  imports:
    - sixtools

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: BSD 3-clause
