{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "0" %}

package:
  name: 05-id-srx-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - hxntools
    - pyxrf >=0.0.9
